### ISSUE TITLE
Add License to Repo

### ISSUE THREAD

**Issue by ccpfoye** [sowcow/fallout-dialogs#11]
I emailed the author of the repo directly about this as well. :) We should add an open-source license so researchers (such as myself) can use this. I recommend the MIT License.

**Comment by sowcow** [comment]
I've never read licenses so I went with the one I wrote myself instead.

**Comment by ccpfoye** [comment]
lol. Love it. Thank you!

**Comment by sowcow** [comment]
No problem!

**Comment by sowcow** [comment]
@ccpfoye, I've added a small clarification that license applies to the code. The content I assume is fine under fair use, it is just out of scope of what I can license here. Hopefully this nonsense does not affect research opportunities in any way.
